from django.urls import path
from .views import (
    home,
    checkout,
    shop,
    detail,
    contact,
    tshirt,
    shirt,
    jacket,
    jeans,
    panjabi,
    pajama,
    polo,
    tops,
    kamiz,
    wallet,
    bag,
    cap,
    sunglasses,
    fullsleeve,
    winter_jacket,
    beauty,
    pant,
    ladies_tshirt_c,
    cart_form,
    cart,
    remove_product_from_cart,
    order,
    create_order,
    beauty,
    seller,
    seller_form,
    became_a_seller,
    upload_product,
    review_form,
    all_product,
    search,
    profile,

)

urlpatterns = [

    path('', home, name='home'),
    path('checkout', checkout, name='checkout'),
    path('shop', shop, name='shop'),
    path('detail/<int:pk>', detail.as_view(), name='detail'),
    path('contact', contact, name='contact'),
    path('tshirt', tshirt, name='tshirt'),
    path('shirt', shirt, name='shirt'),
    path('jacket', jacket, name='jacket'),
    path('jeans', jeans, name='jeans'),
    path('panjabi', panjabi, name='panjabi'),
    path('pajama', pajama, name='pajama'),
    path('polo', polo, name='polo'),
    path('tops', tops, name='tops'),
    path('kamiz', kamiz, name='kamiz'),
    path('wallet', wallet, name='wallet'),
    path('bag', bag, name='bag'),
    path('cap', cap, name='cap'),
    path('sunglasses', sunglasses, name='sunglasses'),
    path('fullsleeve', fullsleeve, name='fullsleeve'),
    path('winter_jacket', winter_jacket, name='winter_jacket'),
    path('beauty', beauty, name='beauty'),
    path('pant', pant, name='pant'),
    path('ladies_tshirt_c', ladies_tshirt_c, name='ladies_tshirt_c'),
    path('cart_form', cart_form, name='cart_form'),
    path('cart', cart, name='cart'),
    path('remove_product/', remove_product_from_cart, name='remove_product_from_cart'),
    path('order/', order, name='order'),
    path('create_order/', create_order, name='create_order'),
    path('beauty/', beauty, name='beauty'),
    path('seller/', seller, name='seller'),
    path('seller_form/', seller_form, name='seller_form'),
    path('became_a_seller/', became_a_seller, name='became_a_seller'),
    path('upload_product/', upload_product, name='upload_product'),
    path('review_form/', review_form, name='review_form'),
    path('all_product/', all_product, name='all_product'),
    path('search/', search, name='search'),
    path('profile/', profile, name='profile'),

]