# Generated by Django 4.2.5 on 2023-09-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=99, null=True)),
                ('product_price', models.IntegerField(blank=True, null=True)),
                ('product_category', models.CharField(blank=True, choices=[('Health Care', 'Category 1'), ('Beauti Product', 'Category 2'), ('Organic', 'Category 3'), ('Physiotherapy', 'Category 3'), ('Hospital Eqquipment', 'Category 3'), ('Surgical Product', 'Category 3'), ('Lab Product', 'Category 3')], max_length=99, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_offer', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
