# Generated by Django 4.2.5 on 2023-09-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_photo_alter_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_offer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
