# Generated by Django 4.2.5 on 2023-09-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_product_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=99, null=True)),
                ('product_price', models.IntegerField(blank=True, null=True)),
                ('product_quantity', models.IntegerField(blank=True, default=0)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
