# Generated by Django 4.2.5 on 2023-09-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_cart_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cart/'),
        ),
    ]
