# Generated by Django 4.2.5 on 2023-09-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_myorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photo/'),
        ),
        migrations.AddField(
            model_name='myorder',
            name='product_name',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='myorder',
            name='product_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
