# Generated by Django 4.2.5 on 2023-09-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_myorder_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myorder',
            old_name='product_name',
            new_name='product_details',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='product_price',
        ),
    ]
