# Generated by Django 4.2.5 on 2023-09-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_merchant_alter_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='username',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
