# Generated by Django 4.2.5 on 2023-09-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_merchant_verified_product_additional_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='verified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
