# Generated by Django 4.2.5 on 2023-09-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_merchant_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='product_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
