# Generated by Django 4.2.5 on 2023-09-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_myorder_date_alter_myorder_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='product_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
