# Generated by Django 4.2.5 on 2023-09-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_myorder_product_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='product_details',
        ),
    ]
