# Generated by Django 4.2.5 on 2023-09-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
