# Generated by Django 4.2.5 on 2023-10-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_delete_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photos',
            field=models.ImageField(blank=True, default='/media/no-photo.jpg', null=True, upload_to='product_photo/'),
        ),
    ]
