# Generated by Django 4.2.5 on 2023-10-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_product_photos_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_photo1',
            field=models.ImageField(blank=True, null=True, upload_to='product_photo/'),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_photo2',
            field=models.ImageField(blank=True, null=True, upload_to='product_photo/'),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_photo3',
            field=models.ImageField(blank=True, null=True, upload_to='product_photo/'),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_photo4',
            field=models.ImageField(blank=True, null=True, upload_to='product_photo/'),
        ),
    ]
