# Generated by Django 4.2.5 on 2023-10-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_cart_product_price_alter_product_product_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('Retail', 'Retail'), ('Wholesale', 'Wholesale')], max_length=99, null=True),
        ),
    ]
