# Generated by Django 5.0.2 on 2024-03-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_remove_product_product_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pant_size',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='size_tshirt',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
