# Generated by Django 5.0.2 on 2024-03-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_myorder_pant_size_myorder_size_tshirt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='pant_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='myorder',
            old_name='pant_size',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='size_tshirt',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='size_tshirt',
        ),
    ]
